name: CI/CD to GitHub Pages

on:
  push:
    branches:
      - main # Thay 'main' bằng branch chính của bạn

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          npm run build -- --configuration production --base-href="/gift-box/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/gift-box/browser
